paths:
  source_folder: E:\projects\temp
  target_folder: E:\projects\temp
  temp_folder: '%TEMP%'
  destination_folder: E:\projects\tmp

settings:
  min_file_size_mb: 800
  prefix: жат-
  ignore_prefix: жат-
  telegram_enabled: false
  auto_update_enabled: false
  modules:
  - convert-subtitles
  - extract-subtitles
  - convert-video
  - copy-to-destination

ffmpeg:
  ffmpeg_path: D:/scoop/shims/ffmpeg.exe

video_extensions:
- .mp4
- .avi
- .mov
- .wmv
- .flv
- .webm
- .mkv
- .m4v

subtitle_extension:
- .vtt
- .srt
- .ass

stabilization_strategy:
  use_file_size_stabilization: true
  stabilization_check_interval_sec: 5
  stabilization_timeout_sec: 600

logging:
  log_file: auto-converter.log

subtitles:
  extract_languages:
  - rus
  - eng
  - zho
  - chi
