paths:
  source_folder: D:\disc\YandexDisk\sync
  target_folder: D:\disc\YandexDisk\sync
  temp_folder: '%TEMP%'
  destination_folder: D:\disc2\Yandex.Disk\Равки 2

settings:
  min_file_size_mb: 800
  prefix: жат-
  ignore_prefix: жат-
  telegram_enabled: true
  auto_update_enabled: false

ffmpeg:
  ffmpeg_path: D:/scoop/shims/ffmpeg.exe

video_extensions:
  - .mp4
  - .avi
  - .mov
  - .wmv
  - .flv
  - .webm
  - .mkv
  - .m4v

subtitle_extension:
  - .vtt
  - .srt

stabilization_strategy:
  use_file_size_stabilization: true
  stabilization_check_interval_sec: 5
  stabilization_timeout_sec: 600

logging:
  log_file: auto-converter.log